apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ispend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: zasviat/ispend:latest
          ports:
            - containerPort: 8000

          envFrom:
            - secretRef:
                name: app-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ispend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
